/** Phase 1 catalog: cars and cities. Slugs are stable identifiers; edit names freely. */

export const CITIES: Array<{ name: string; state: string; slug: string }> = [
  { name: 'Ahmedabad', state: 'Gujarat', slug: 'ahmedabad' },
  { name: 'Surat', state: 'Gujarat', slug: 'surat' },
  { name: 'Vadodara', state: 'Gujarat', slug: 'vadodara' },
  { name: 'Rajkot', state: 'Gujarat', slug: 'rajkot' },
  { name: 'Mumbai', state: 'Maharashtra', slug: 'mumbai' },
  { name: 'Pune', state: 'Maharashtra', slug: 'pune' },
  { name: 'Nagpur', state: 'Maharashtra', slug: 'nagpur' },
  { name: 'Delhi', state: 'Delhi', slug: 'delhi' },
  { name: 'Gurugram', state: 'Haryana', slug: 'gurugram' },
  { name: 'Noida', state: 'Uttar Pradesh', slug: 'noida' },
  { name: 'Lucknow', state: 'Uttar Pradesh', slug: 'lucknow' },
  { name: 'Jaipur', state: 'Rajasthan', slug: 'jaipur' },
  { name: 'Bengaluru', state: 'Karnataka', slug: 'bengaluru' },
  { name: 'Hyderabad', state: 'Telangana', slug: 'hyderabad' },
  { name: 'Chennai', state: 'Tamil Nadu', slug: 'chennai' },
  { name: 'Coimbatore', state: 'Tamil Nadu', slug: 'coimbatore' },
  { name: 'Kolkata', state: 'West Bengal', slug: 'kolkata' },
  { name: 'Indore', state: 'Madhya Pradesh', slug: 'indore' },
  { name: 'Bhopal', state: 'Madhya Pradesh', slug: 'bhopal' },
  { name: 'Chandigarh', state: 'Chandigarh', slug: 'chandigarh' },
  { name: 'Kochi', state: 'Kerala', slug: 'kochi' },
  { name: 'Thiruvananthapuram', state: 'Kerala', slug: 'thiruvananthapuram' },
  { name: 'Bhubaneswar', state: 'Odisha', slug: 'bhubaneswar' },
  { name: 'Patna', state: 'Bihar', slug: 'patna' },
  { name: 'Visakhapatnam', state: 'Andhra Pradesh', slug: 'visakhapatnam' },
];

export const CARS: Array<{ brand: string; model: string }> = [
  { brand: 'Maruti Suzuki', model: 'Swift' },
  { brand: 'Maruti Suzuki', model: 'Baleno' },
  { brand: 'Maruti Suzuki', model: 'Dzire' },
  { brand: 'Maruti Suzuki', model: 'Brezza' },
  { brand: 'Maruti Suzuki', model: 'Grand Vitara' },
  { brand: 'Maruti Suzuki', model: 'Ertiga' },
  { brand: 'Maruti Suzuki', model: 'Fronx' },
  { brand: 'Maruti Suzuki', model: 'Wagon R' },
  { brand: 'Hyundai', model: 'Creta' },
  { brand: 'Hyundai', model: 'Venue' },
  { brand: 'Hyundai', model: 'i20' },
  { brand: 'Hyundai', model: 'Verna' },
  { brand: 'Hyundai', model: 'Exter' },
  { brand: 'Hyundai', model: 'Alcazar' },
  { brand: 'Tata', model: 'Nexon' },
  { brand: 'Tata', model: 'Punch' },
  { brand: 'Tata', model: 'Harrier' },
  { brand: 'Tata', model: 'Safari' },
  { brand: 'Tata', model: 'Curvv' },
  { brand: 'Tata', model: 'Altroz' },
  { brand: 'Tata', model: 'Tiago' },
  { brand: 'Mahindra', model: 'Scorpio-N' },
  { brand: 'Mahindra', model: 'XUV700' },
  { brand: 'Mahindra', model: 'XUV 3XO' },
  { brand: 'Mahindra', model: 'Thar' },
  { brand: 'Mahindra', model: 'Thar Roxx' },
  { brand: 'Mahindra', model: 'Bolero' },
  { brand: 'Kia', model: 'Seltos' },
  { brand: 'Kia', model: 'Sonet' },
  { brand: 'Kia', model: 'Carens' },
  { brand: 'Kia', model: 'Syros' },
  { brand: 'Toyota', model: 'Innova Crysta' },
  { brand: 'Toyota', model: 'Innova Hycross' },
  { brand: 'Toyota', model: 'Fortuner' },
  { brand: 'Toyota', model: 'Urban Cruiser Hyryder' },
  { brand: 'Toyota', model: 'Glanza' },
  { brand: 'Honda', model: 'City' },
  { brand: 'Honda', model: 'Amaze' },
  { brand: 'Honda', model: 'Elevate' },
  { brand: 'Skoda', model: 'Kushaq' },
  { brand: 'Skoda', model: 'Slavia' },
  { brand: 'Skoda', model: 'Kylaq' },
  { brand: 'Volkswagen', model: 'Taigun' },
  { brand: 'Volkswagen', model: 'Virtus' },
  { brand: 'MG', model: 'Hector' },
  { brand: 'MG', model: 'Astor' },
  { brand: 'MG', model: 'Windsor EV' },
  { brand: 'Renault', model: 'Kiger' },
  { brand: 'Renault', model: 'Triber' },
  { brand: 'Nissan', model: 'Magnite' },
  { brand: 'Citroen', model: 'C3' },
  { brand: 'Jeep', model: 'Compass' },
];

export function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}
